name: Build Vue
on:
  push:
    branches:
      - main
jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v2

    - name: Build and Deploy
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'hhannaarvid'
        reponame: 'ssr-frontend'
        token: ${{ secrets.GITHUB_TOKEN }}