name: Build and Deploy Vue

on:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build and Deploy
        uses: xRealNeon/VuePagesAction@v1.0.1
        with:
          username: hhannaarvid
          reponame: ssr-frontend
          token: ${{ secrets.GITHUB_TOKEN }}